/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ivanderlibrary;

import java.awt.Color;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mfarr
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    Color EnterColor = new Color(180, 132, 108);
    Color ExitColor = new Color(229, 178, 153);
    Color EnterLogout = new Color(0,0,0);
    Color ExitLogout = new Color(255,255,255);
            
    public Homepage() {
        initComponents();
        labelNoOfBooks.setText( String.valueOf( getCountNoOfBooks() ) );
        labelNoOfCustomers.setText( String.valueOf( getCountNoOfCustomers() ) );
        labelNoOfBorrowings.setText( String.valueOf( getCountNoOfBorrowings() ) );
        labelNoOfReturns.setText( String.valueOf( getCountNoOfReturn() ) );
        labelBooksOnLoans.setText( String.valueOf( getCountBooksOnLoan() ) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        labelNoOfBooks = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        labelNoOfCustomers = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        labelNoOfBorrowings = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        labelNoOfReturns = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        labelBooksOnLoans = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_Admin = new javax.swing.JLabel();
        Panel_BBook = new javax.swing.JPanel();
        lbl_BBook = new javax.swing.JLabel();
        Panel_MBook = new javax.swing.JPanel();
        lbl_ManageBook = new javax.swing.JLabel();
        Panel_RBook = new javax.swing.JPanel();
        lbl_RBook = new javax.swing.JLabel();
        Panel_CBook = new javax.swing.JPanel();
        lbl_CBook = new javax.swing.JLabel();
        Panel_Record = new javax.swing.JPanel();
        lbl_Record = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_Logout = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lbl_Logout1 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        lbl_Logout2 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        lbl_Logout3 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/log000.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(180, 132, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrator");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 20, 130, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("IVANDER LIBRARY | Discover New World With Library");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 600, -1));

        jButton1.setBackground(new java.awt.Color(180, 132, 108));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 910, 70));

        jPanel3.setBackground(new java.awt.Color(180, 132, 108));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Home Page");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel13.setBackground(new java.awt.Color(180, 132, 108));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Home Page");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 50));

        jPanel14.setBackground(new java.awt.Color(180, 132, 108));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Home Page");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel15.setBackground(new java.awt.Color(180, 132, 108));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Home Page");
        jPanel15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 50));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 50));

        jPanel5.setBackground(new java.awt.Color(252, 222, 192));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(229, 178, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(252, 222, 192));

        jPanel12.setBackground(new java.awt.Color(180, 132, 108));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(180, 132, 108));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No. Of Books :");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, -1));

        labelNoOfBooks.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        labelNoOfBooks.setForeground(new java.awt.Color(0, 0, 0));
        labelNoOfBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoOfBooks.setText("4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(labelNoOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNoOfBooks)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 210, 130));

        jPanel9.setBackground(new java.awt.Color(252, 222, 192));

        jPanel17.setBackground(new java.awt.Color(180, 132, 108));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(180, 132, 108));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("No. Of Customers :");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        labelNoOfCustomers.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        labelNoOfCustomers.setForeground(new java.awt.Color(0, 0, 0));
        labelNoOfCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoOfCustomers.setText("4");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(labelNoOfCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNoOfCustomers)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 210, 130));

        jPanel11.setBackground(new java.awt.Color(252, 222, 192));

        jPanel18.setBackground(new java.awt.Color(180, 132, 108));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(180, 132, 108));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("No. Of Borrowings :");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelNoOfBorrowings.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        labelNoOfBorrowings.setForeground(new java.awt.Color(0, 0, 0));
        labelNoOfBorrowings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoOfBorrowings.setText("4");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(labelNoOfBorrowings, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNoOfBorrowings)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 200, 130));

        jPanel20.setBackground(new java.awt.Color(252, 222, 192));

        jPanel21.setBackground(new java.awt.Color(180, 132, 108));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(180, 132, 108));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("No. Of Returns :");
        jPanel22.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        labelNoOfReturns.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        labelNoOfReturns.setForeground(new java.awt.Color(0, 0, 0));
        labelNoOfReturns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoOfReturns.setText("4");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(labelNoOfReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNoOfReturns)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 130));

        jPanel23.setBackground(new java.awt.Color(252, 222, 192));

        jPanel24.setBackground(new java.awt.Color(180, 132, 108));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(180, 132, 108));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Books On Loan :");
        jPanel25.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, -1));

        labelBooksOnLoans.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        labelBooksOnLoans.setForeground(new java.awt.Color(0, 0, 0));
        labelBooksOnLoans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBooksOnLoans.setText("4");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelBooksOnLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBooksOnLoans)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 210, 130));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 830, 520));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("2023 Group 3_2SE2_CCIT-FTUI");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 220, 30));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Home Page");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 910, 620));

        jPanel2.setBackground(new java.awt.Color(229, 178, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Admin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lbl_Admin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Admin.setText("Administrator");
        jPanel2.add(lbl_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        Panel_BBook.setBackground(new java.awt.Color(229, 178, 153));
        Panel_BBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_BBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_BBookMouseClicked(evt);
            }
        });
        Panel_BBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_BBook.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_BBook.setForeground(new java.awt.Color(0, 0, 0));
        lbl_BBook.setText("Borrow Book");
        lbl_BBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_BBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BBookMouseExited(evt);
            }
        });
        Panel_BBook.add(lbl_BBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        getContentPane().add(Panel_BBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 50));

        Panel_MBook.setBackground(new java.awt.Color(229, 178, 153));
        Panel_MBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_MBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_MBookMouseClicked(evt);
            }
        });
        Panel_MBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ManageBook.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_ManageBook.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ManageBook.setText("Manage Book");
        lbl_ManageBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ManageBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ManageBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ManageBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ManageBookMouseExited(evt);
            }
        });
        Panel_MBook.add(lbl_ManageBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        getContentPane().add(Panel_MBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 50));

        Panel_RBook.setBackground(new java.awt.Color(229, 178, 153));
        Panel_RBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_RBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_RBookMouseClicked(evt);
            }
        });
        Panel_RBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_RBook.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_RBook.setForeground(new java.awt.Color(0, 0, 0));
        lbl_RBook.setText("Return Book");
        lbl_RBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_RBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RBookMouseExited(evt);
            }
        });
        Panel_RBook.add(lbl_RBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        getContentPane().add(Panel_RBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        Panel_CBook.setBackground(new java.awt.Color(229, 178, 153));
        Panel_CBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_CBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_CBookMouseClicked(evt);
            }
        });
        Panel_CBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_CBook.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_CBook.setForeground(new java.awt.Color(0, 0, 0));
        lbl_CBook.setText("Customer");
        lbl_CBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_CBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CBookMouseExited(evt);
            }
        });
        Panel_CBook.add(lbl_CBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        getContentPane().add(Panel_CBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 50));

        Panel_Record.setBackground(new java.awt.Color(229, 178, 153));
        Panel_Record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_RecordMouseClicked(evt);
            }
        });
        Panel_Record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Record.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_Record.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Record.setText("View All Record");
        lbl_Record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RecordMouseExited(evt);
            }
        });
        Panel_Record.add(lbl_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        getContentPane().add(Panel_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 50));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Manage Book");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Manage Book");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel4.setBackground(new java.awt.Color(180, 132, 108));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Logout.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_Logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Logout.setText("Logout");
        lbl_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_LogoutMouseExited(evt);
            }
        });
        jPanel4.add(lbl_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 159, 50));

        jPanel16.setBackground(new java.awt.Color(229, 178, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Logout1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbl_Logout1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Logout1.setText("Logout");
        lbl_Logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_Logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_Logout1MouseExited(evt);
            }
        });
        jPanel16.add(lbl_Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 159, 50));

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 50));

        jPanel26.setBackground(new java.awt.Color(229, 178, 153));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Logout2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbl_Logout2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Logout2.setText("Logout");
        lbl_Logout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Logout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_Logout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_Logout2MouseExited(evt);
            }
        });
        jPanel26.add(lbl_Logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 159, 50));

        jPanel27.setBackground(new java.awt.Color(229, 178, 153));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Logout3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbl_Logout3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Logout3.setText("Logout");
        lbl_Logout3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Logout3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_Logout3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_Logout3MouseExited(evt);
            }
        });
        jPanel27.add(lbl_Logout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 159, 50));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 50));

        jPanel4.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 50));

        jPanel28.setBackground(new java.awt.Color(229, 178, 153));
        jPanel28.setForeground(new java.awt.Color(229, 178, 153));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // get count 
    private int getCountNoOfBooks(){
        int count = -1;
        
        try {
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT COUNT(*) FROM `book_details`";
            PreparedStatement prp = cn.prepareStatement(sql);
            ResultSet resultData = prp.executeQuery();
            
            resultData.next();
            count = resultData.getInt(1);
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
    
    private int getCountNoOfCustomers(){
        int count = -1;
        
        try {
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT COUNT(*) FROM `customer`";
            PreparedStatement prp = cn.prepareStatement(sql);
            ResultSet resultData = prp.executeQuery();
            
            resultData.next();
            count = resultData.getInt(1);
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
    
    private int getCountNoOfBorrowings(){
        int count = -1;
        
        try {
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT COUNT(*) FROM `issue_book`";
            PreparedStatement prp = cn.prepareStatement(sql);
            ResultSet resultData = prp.executeQuery();
            
            resultData.next();
            count = resultData.getInt(1);
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
    
    private int getCountNoOfReturn(){
        int count = -1;
        
        try {
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT COUNT(*) FROM `issue_book` WHERE Status = 'Returned'";
            PreparedStatement prp = cn.prepareStatement(sql);
            ResultSet resultData = prp.executeQuery();
            
            resultData.next();
            count = resultData.getInt(1);
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
    
    private int getCountBooksOnLoan(){
        int count = -1;
        
        try {
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT COUNT(*) FROM `issue_book` WHERE Status = 'Issued'";
            PreparedStatement prp = cn.prepareStatement(sql);
            ResultSet resultData = prp.executeQuery();
            
            resultData.next();
            count = resultData.getInt(1);
            
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return count;
    }
    
    
    private void lbl_ManageBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ManageBookMouseClicked
        ManageBook MPage = new ManageBook();
        MPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_ManageBookMouseClicked

    private void Panel_MBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_MBookMouseClicked
        ManageBook MPage = new ManageBook();
        MPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_MBookMouseClicked

    private void lbl_BBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BBookMouseClicked
        BorrowBook BPage = new BorrowBook();
        BPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BBookMouseClicked

    private void Panel_BBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_BBookMouseClicked
        BorrowBook BPage = new BorrowBook();
        BPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_BBookMouseClicked

    private void lbl_RBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RBookMouseClicked
        ReturnBook RPage = new ReturnBook();
        RPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_RBookMouseClicked

    private void Panel_RBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_RBookMouseClicked
        ReturnBook RPage = new ReturnBook();
        RPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_RBookMouseClicked

    private void lbl_CBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CBookMouseClicked
        Customer CPage = new Customer();
        CPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_CBookMouseClicked

    private void Panel_CBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_CBookMouseClicked
        Customer CPage = new Customer();
        CPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_CBookMouseClicked

    private void lbl_RecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RecordMouseClicked
        ViewAllRecord VPage = new ViewAllRecord();
        VPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_RecordMouseClicked

    private void Panel_RecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_RecordMouseClicked
        ViewAllRecord VPage = new ViewAllRecord();
        VPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_RecordMouseClicked

    private void lbl_ManageBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ManageBookMouseEntered
        Panel_MBook.setBackground(EnterColor);
    }//GEN-LAST:event_lbl_ManageBookMouseEntered

    private void lbl_ManageBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ManageBookMouseExited
        Panel_MBook.setBackground(ExitColor);
    }//GEN-LAST:event_lbl_ManageBookMouseExited

    private void lbl_BBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BBookMouseEntered
        Panel_BBook.setBackground(EnterColor);
    }//GEN-LAST:event_lbl_BBookMouseEntered

    private void lbl_BBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BBookMouseExited
        Panel_BBook.setBackground(ExitColor);
    }//GEN-LAST:event_lbl_BBookMouseExited

    private void lbl_RBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RBookMouseEntered
        Panel_RBook.setBackground(EnterColor);
    }//GEN-LAST:event_lbl_RBookMouseEntered

    private void lbl_RBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RBookMouseExited
        Panel_RBook.setBackground(ExitColor);
    }//GEN-LAST:event_lbl_RBookMouseExited

    private void lbl_CBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CBookMouseEntered
        Panel_CBook.setBackground(EnterColor);
    }//GEN-LAST:event_lbl_CBookMouseEntered

    private void lbl_CBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CBookMouseExited
        Panel_CBook.setBackground(ExitColor);
    }//GEN-LAST:event_lbl_CBookMouseExited

    private void lbl_RecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RecordMouseEntered
        Panel_Record.setBackground(EnterColor);
    }//GEN-LAST:event_lbl_RecordMouseEntered

    private void lbl_RecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RecordMouseExited
        Panel_Record.setBackground(ExitColor);
    }//GEN-LAST:event_lbl_RecordMouseExited

    private void lbl_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogoutMouseClicked
        Login LPage = new Login();
        LPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_LogoutMouseClicked

    private void lbl_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogoutMouseEntered
        lbl_Logout.setForeground(EnterLogout);
    }//GEN-LAST:event_lbl_LogoutMouseEntered

    private void lbl_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogoutMouseExited
        lbl_Logout.setForeground(ExitLogout);
    }//GEN-LAST:event_lbl_LogoutMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_Logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout1MouseClicked

    private void lbl_Logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout1MouseEntered

    private void lbl_Logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout1MouseExited

    private void lbl_Logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout2MouseClicked

    private void lbl_Logout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout2MouseEntered

    private void lbl_Logout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout2MouseExited

    private void lbl_Logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout3MouseClicked

    private void lbl_Logout3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout3MouseEntered

    private void lbl_Logout3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Logout3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Logout3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_BBook;
    private javax.swing.JPanel Panel_CBook;
    private javax.swing.JPanel Panel_MBook;
    private javax.swing.JPanel Panel_RBook;
    private javax.swing.JPanel Panel_Record;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelBooksOnLoans;
    private javax.swing.JLabel labelNoOfBooks;
    private javax.swing.JLabel labelNoOfBorrowings;
    private javax.swing.JLabel labelNoOfCustomers;
    private javax.swing.JLabel labelNoOfReturns;
    private javax.swing.JLabel lbl_Admin;
    private javax.swing.JLabel lbl_BBook;
    private javax.swing.JLabel lbl_CBook;
    private javax.swing.JLabel lbl_Logout;
    private javax.swing.JLabel lbl_Logout1;
    private javax.swing.JLabel lbl_Logout2;
    private javax.swing.JLabel lbl_Logout3;
    private javax.swing.JLabel lbl_ManageBook;
    private javax.swing.JLabel lbl_RBook;
    private javax.swing.JLabel lbl_Record;
    // End of variables declaration//GEN-END:variables
}
