/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ivanderlibrary;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mfarr
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public ReturnBook() {
        initComponents();
    }
    private void clearTextField(){
        txf_BookID.setText(null);
        txf_CustomerID.setText(null);
  
    }
    
    public boolean getIssueBook(int BookID, int CustomerID){
        boolean getIssueBook = false;
        try{
            Connection cn = ConnectionDB.getConnection();
            String sql = "SELECT issue_book.IssueID, book_details.Title, customer.Name, issue_book.IssueDate, issue_book.DueDate, issue_book.Status FROM "
                    + "issue_book JOIN book_details ON issue_book.BookID = book_details.BookID JOIN "
                    + "customer ON issue_book.CustomerID = customer.CustomerID WHERE issue_book.BookID = ? and issue_book.CustomerID = ? and issue_book.Status = ?";
            PreparedStatement prp = cn.prepareStatement(sql);
            
            prp.setInt(1, BookID);
            prp.setInt(2,CustomerID);
            prp.setString(3, "Issued");
            
            ResultSet rs = prp.executeQuery();
            if(rs.next()){
                emp_IssueID.setText(Integer.toString(rs.getInt("issue_book.IssueID")));
                emp_Title.setText(rs.getString("book_details.Title"));
                emp_Name.setText(rs.getString("customer.Name"));
                emp_IssueDate.setText(rs.getString("issue_book.IssueDate"));
                emp_DueDate.setText(rs.getString("issue_book.DueDate"));
                emp_Invalid.setText("");
            }else{
                emp_IssueID.setText("");
                emp_Title.setText("");
                emp_Name.setText("");
                emp_IssueDate.setText("");
                emp_DueDate.setText("");
                emp_Invalid.setText("NOT FOUND");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return getIssueBook;
    }
    public boolean returnBook(int BookID, int CustomerID){
        boolean Returned = false;
        try{
            Connection cn = ConnectionDB.getConnection();
            String sql = "update issue_book set Status = ? where CustomerID = ? and BookId = ? and Status = ?";
            PreparedStatement prp = cn.prepareStatement(sql);
            prp.setString(1, "Returned");
            prp.setInt(2, CustomerID);
            prp.setInt(3, BookID);
            prp.setString(4,"Issued");
            
            int RowCount = prp.executeUpdate();
            if(RowCount > 0){
                Returned = true;
            }else{
                Returned = false;
            }
        }catch(Exception e){
            
        }
        return Returned = true;
    }
    public void updateQuantity(int BookID){
        try{
            Connection cn = ConnectionDB.getConnection();
            String sql = "update book_details set Quantity = Quantity + 1 where BookID = ?";
            PreparedStatement prp = cn.prepareStatement(sql);
            prp.setInt(1, BookID);
            
            int rowCount = prp.executeUpdate();
            
            if(rowCount > 0 ){
                JOptionPane.showMessageDialog(this, "Updated");
            }else {
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txf_BookID = new app.bolivia.swing.JCTextField();
        btn_returnBook = new javax.swing.JButton();
        txf_CustomerID = new app.bolivia.swing.JCTextField();
        btn_Find = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        emp_Title = new javax.swing.JLabel();
        emp_IssueID = new javax.swing.JLabel();
        emp_Name = new javax.swing.JLabel();
        emp_IssueDate = new javax.swing.JLabel();
        emp_DueDate = new javax.swing.JLabel();
        emp_Invalid = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_HomePage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/log000.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(229, 178, 153));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Book ID");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Customer ID");

        txf_BookID.setBackground(new java.awt.Color(229, 178, 153));
        txf_BookID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 132, 108)));
        txf_BookID.setForeground(new java.awt.Color(0, 0, 0));
        txf_BookID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_BookID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txf_BookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_BookIDActionPerformed(evt);
            }
        });

        btn_returnBook.setBackground(new java.awt.Color(180, 132, 108));
        btn_returnBook.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_returnBook.setForeground(new java.awt.Color(255, 255, 255));
        btn_returnBook.setText("Return Book");
        btn_returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnBookActionPerformed(evt);
            }
        });

        txf_CustomerID.setBackground(new java.awt.Color(229, 178, 153));
        txf_CustomerID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 132, 108)));
        txf_CustomerID.setForeground(new java.awt.Color(0, 0, 0));
        txf_CustomerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_CustomerID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btn_Find.setBackground(new java.awt.Color(180, 132, 108));
        btn_Find.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_Find.setForeground(new java.awt.Color(255, 255, 255));
        btn_Find.setText("Find ");
        btn_Find.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_BookID, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(txf_CustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_returnBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Find, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_Find)
                .addGap(18, 18, 18)
                .addComponent(btn_returnBook)
                .addGap(190, 190, 190))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 690));

        jPanel5.setBackground(new java.awt.Color(252, 222, 192));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(229, 178, 153));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Issue ID        :");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Title              : ");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Issue Date    :");

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Name            :");

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Due Date      :");

        emp_Title.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emp_Title.setForeground(new java.awt.Color(0, 0, 0));

        emp_IssueID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emp_IssueID.setForeground(new java.awt.Color(0, 0, 0));

        emp_Name.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emp_Name.setForeground(new java.awt.Color(0, 0, 0));

        emp_IssueDate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emp_IssueDate.setForeground(new java.awt.Color(0, 0, 0));

        emp_DueDate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emp_DueDate.setForeground(new java.awt.Color(0, 0, 0));

        emp_Invalid.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        emp_Invalid.setForeground(new java.awt.Color(255, 0, 51));
        emp_Invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(emp_IssueID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emp_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emp_IssueDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emp_DueDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(emp_Invalid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_IssueID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emp_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emp_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_DueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(emp_Invalid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 570, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Return Book");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 220, 30));

        btn_HomePage.setBackground(new java.awt.Color(180, 132, 108));
        btn_HomePage.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_HomePage.setForeground(new java.awt.Color(255, 255, 255));
        btn_HomePage.setText("<< HOME PAGE");
        btn_HomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomePageActionPerformed(evt);
            }
        });
        jPanel5.add(btn_HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        jButton1.setBackground(new java.awt.Color(180, 132, 108));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 63, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 780, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnBookActionPerformed
    if(returnBook(Integer.parseInt(txf_BookID.getText()), Integer.parseInt(txf_CustomerID.getText())) == true){
        JOptionPane.showMessageDialog(this, "Succes");
        updateQuantity(Integer.parseInt(txf_BookID.getText()));
        clearTextField();
    }else {
        JOptionPane.showMessageDialog(this, "Failed");
    }
    }//GEN-LAST:event_btn_returnBookActionPerformed

    private void txf_BookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_BookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_BookIDActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        getIssueBook(Integer.parseInt(txf_BookID.getText()), Integer.parseInt(txf_CustomerID.getText()));
    }//GEN-LAST:event_btn_FindActionPerformed

    private void btn_HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomePageActionPerformed
        Homepage HPage = new Homepage();
        HPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomePageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_HomePage;
    private javax.swing.JButton btn_returnBook;
    private javax.swing.JLabel emp_DueDate;
    private javax.swing.JLabel emp_Invalid;
    private javax.swing.JLabel emp_IssueDate;
    private javax.swing.JLabel emp_IssueID;
    private javax.swing.JLabel emp_Name;
    private javax.swing.JLabel emp_Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private app.bolivia.swing.JCTextField txf_BookID;
    private app.bolivia.swing.JCTextField txf_CustomerID;
    // End of variables declaration//GEN-END:variables
}
