/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ivanderlibrary;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author mfarr
 */



public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    DefaultTableModel model;
    public ViewAllRecord() {
        initComponents();
        insertIssueBook();
    }
    
    
    
    public void insertIssueBook(){
        try{
            Connection cn = ConnectionDB.getConnection();
            Statement state = cn.createStatement();
            String sql = "SELECT issue_book.IssueID, book_details.Title, customer.Name, issue_book.IssueDate, issue_book.DueDate,"
                    + " issue_book.Status FROM issue_book JOIN book_details ON issue_book.BookID = book_details.BookID "
                    + "JOIN customer ON issue_book.CustomerID = customer.CustomerID";
            ResultSet rs = state.executeQuery(sql);
            
            while(rs.next()){
                int IssueID = rs.getInt("issue_book.IssueID");
                String Title = rs.getString("book_details.Title");
                String CustomerName = rs.getString("customer.Name");
                String IssueDate = rs.getString("issue_book.IssueDate");
                String DueDate = rs.getString("issue_book.DueDate");
                String Status = rs.getString("issue_book.Status");
                
                Object[] obj = {IssueID,Title,CustomerName,IssueDate,DueDate,Status};
                model = (DefaultTableModel) tbl_IssueBook.getModel();
                model.addRow(obj);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void search(){
        try{
        Connection cn = ConnectionDB.getConnection();
        Statement st = cn.createStatement();
        String sql = "SELECT issue_book.IssueID, book_details.Title, customer.Name, issue_book.IssueDate, issue_book.DueDate,"
                    + " issue_book.Status FROM issue_book JOIN book_details ON issue_book.BookID = book_details.BookID "
                    + "JOIN customer ON issue_book.CustomerID = customer.CustomerID WHERE " + cmb_Find.getSelectedItem().toString() + " LIKE '%" + txf_Find.getText() + "%'";
        ResultSet rs = st.executeQuery(sql);
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("IssueID");
        model.addColumn("Title");
        model.addColumn("Customer Name");
        model.addColumn("IssueDate");
        model.addColumn("DueDate");
        model.addColumn("Status");
        
        
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        model.setRowCount(0);
        
        while(rs.next()){
            Object[] data = {
               
            rs.getInt("issue_book.IssueID"),
            rs.getString("book_details.Title"),
            rs.getString("customer.Name"),
            rs.getString("issue_book.IssueDate"),
            rs.getString("issue_book.DueDate"),
            rs.getString("issue_book.Status"),
            };
            model.addRow(data);
            tbl_IssueBook.setModel(model);
        }
        
        }catch (Exception e){
            e.printStackTrace();;
        }
        
    }
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_IssueBook.getModel();
        model.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_HomePage = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cmb_Find = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_IssueBook = new rojeru_san.complementos.RSTableMetro();
        txf_Find = new app.bolivia.swing.JCTextField();
        jLabel20 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/log000.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 178, 153));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("View All Record");

        jButton1.setBackground(new java.awt.Color(180, 132, 108));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_HomePage.setBackground(new java.awt.Color(180, 132, 108));
        btn_HomePage.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btn_HomePage.setForeground(new java.awt.Color(255, 255, 255));
        btn_HomePage.setText("<< HOME PAGE");
        btn_HomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_HomePage)
                .addGap(234, 234, 234)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_HomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 70));

        jPanel5.setBackground(new java.awt.Color(252, 222, 192));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(229, 178, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_Find.setBackground(new java.awt.Color(229, 178, 153));
        cmb_Find.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cmb_Find.setForeground(new java.awt.Color(0, 0, 0));
        cmb_Find.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Name", "Status", "IssueDate", "DueDate" }));
        cmb_Find.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_FindActionPerformed(evt);
            }
        });
        jPanel6.add(cmb_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, 40));

        tbl_IssueBook.setAutoCreateRowSorter(true);
        tbl_IssueBook.setBackground(new java.awt.Color(252, 222, 192));
        tbl_IssueBook.setForeground(new java.awt.Color(0, 0, 0));
        tbl_IssueBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Title", "Customer Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_IssueBook.setColorBackgoundHead(new java.awt.Color(255, 204, 0));
        tbl_IssueBook.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_IssueBook.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tbl_IssueBook.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tbl_IssueBook.setRowHeight(35);
        jScrollPane2.setViewportView(tbl_IssueBook);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1020, 290));

        txf_Find.setBackground(new java.awt.Color(229, 178, 153));
        txf_Find.setForeground(new java.awt.Color(0, 0, 0));
        txf_Find.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_Find.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txf_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txf_FindKeyReleased(evt);
            }
        });
        jPanel6.add(txf_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 330, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1040, 520));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("2023 Group 3_2SE2_CCIT-FTUI");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 220, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1120, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_FindActionPerformed

    private void btn_HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomePageActionPerformed
       Homepage HPage = new Homepage();
       HPage.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_HomePageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txf_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_FindKeyReleased
        search();
    }//GEN-LAST:event_txf_FindKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HomePage;
    private javax.swing.JComboBox<String> cmb_Find;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro tbl_IssueBook;
    private app.bolivia.swing.JCTextField txf_Find;
    // End of variables declaration//GEN-END:variables
}
